### ISSUE TITLE
Kits sold out, ideas

### ISSUE THREAD

**Issue by xfbs** [DudeYarvie/JARViE_Home_Automation_Modem#4]
Hey Yarvie,

this is some really awesome stuff. I've always thought it would be a cool idea to have a DIY powerline home automation setup, it just makes sense. Got some questions for ya:

* The kits are currently sold out, are you planning to make some more?
* Would it be possible to monitor the amps going out of the kit? I think that would be cool, imagine being able to monitor your house's power consumption in real time.
* Wouldn't it be cool if the handshake between master and slave units used some kind of cryptographic pairing (I'm thinking elliptic curve based), so that you can avoid 'attacks' or the neighbors snooping traffic/controlling devices?

So many cool possibilities here.

**Comment by DudeYarvie** [comment]
**The kits are currently sold out, are you planning to make some more?**

_Tindie has just been updated with two more boards in stock.  Two boards are required for one kit._  

_You're exactly right, there are so many ideas!  The development boards/kit enable the possibility to explore all those ideas.  Boards will ship 1 to 2 days after order._

**Would it be possible to monitor the amps going out of the kit? I think that would be cool, imagine being able to monitor your house's power consumption in real time.**

_With modification one could monitor amps going out of the kit but not with the existing hardware design._

**Wouldn't it be cool if the handshake between master and slave units used some kind of cryptographic pairing (I'm thinking elliptic curve based), so that you can avoid 'attacks' or the neighbors snooping traffic/controlling devices?**

_Yes, it would totally be cool!  The customizable cryptic pairing possibilities are endless!  People should explore and share them here._

**Comment by DudeYarvie** [comment]
I found this cool IC for power monitoring, MPN: ACS37800KMACTR-090B3-I2C
